services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/djangoblog/static
      - db_data:/djangoblog
    env_file:
      - .env
    ports:
      - "8000:8000"
    container_name: djangoblog_gunicorn

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn
    container_name: djangoblog_nginx

volumes:
  static:
    name: djangoblog_static
  db_data:
    name: djangoblog_db
