version: '3.8'

services:
  django_gunicorn:
    build:
      context: .
    volumes:
      - static:/djangoblog/static
      - db_data:/djangoblog
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - django_gunicorn

volumes:
  static:
  db_data:
